services:
  wol:
    image: "huakunshen/wol"
    container_name: wol-web
    network_mode: host
    volumes:
      - wol_data:/app/pb_data
    environment:
      - SUPERUSER_EMAIL=root@example.com
      - SUPERUSER_PASSWORD=changeme
      - PORT=8090
volumes:
  wol_data:
